/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.restadoapp.androidpauseresume;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;

import org.appcelerator.kroll.KrollDict;


@Kroll.module(name="Androidpauseresume", id="com.restadoapp.androidpauseresume")
public class AndroidpauseresumeModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "AndroidpauseresumeModule";
	private static final boolean DBG = TiConfig.LOGD;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AndroidpauseresumeModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	@Override
    protected void initActivity(Activity activity) {
        Log.d(LCAT, "initActivity " + activity);
        super.initActivity(activity);
    }

    @Override
    public void onResume(Activity activity) {
    	
        Log.d(LCAT, "onResume " + activity);
        
        KrollDict obj = new KrollDict();
        
    	obj.put("onResume", true);
    	obj.put("onPause", false);
    	obj.put("onDestroy", false);
    	obj.put("onStart", false);
    	obj.put("onStop", false);
    	
    	fireEvent("change", obj);
        
        super.onResume(activity);
    }

    @Override
    public void onPause(Activity activity) {
    	
        Log.d(LCAT, "onPause " + activity);
        
        KrollDict obj = new KrollDict();
        
    	obj.put("onResume", false);
    	obj.put("onPause", true);
    	obj.put("onDestroy", false);
    	obj.put("onStart", false);
    	obj.put("onStop", false);
    	
    	fireEvent("change", obj);
        
        super.onPause(activity);
    }

    @Override
    public void onDestroy(Activity activity) {
    	
        Log.d(LCAT, "onDestroy " + activity);
        
        KrollDict obj = new KrollDict();
        
    	obj.put("onResume", false);
    	obj.put("onPause", false);
    	obj.put("onDestroy", true);
    	obj.put("onStart", false);
    	obj.put("onStop", false);
    	
    	fireEvent("change", obj);
        
        super.onDestroy(activity);
    }

    @Override
    public void onStart(Activity activity) {
    	
        Log.d(LCAT, "onStart " + activity);
        
        KrollDict obj = new KrollDict();
        
    	obj.put("onResume", false);
    	obj.put("onPause", false);
    	obj.put("onDestroy", false);
    	obj.put("onStart", true);
    	obj.put("onStop", false);
    	
    	fireEvent("change", obj);
        
        super.onStart(activity);
    }

    @Override
    public void onStop(Activity activity) {
    	
        Log.d(LCAT, "onStop " + activity);
        
        KrollDict obj = new KrollDict();
        
    	obj.put("onResume", false);
    	obj.put("onPause", false);
    	obj.put("onDestroy", false);
    	obj.put("onStart", false);
    	obj.put("onStop", true);
    	
    	fireEvent("change", obj);
        
        super.onStop(activity);
    }


}

